### ISSUE TITLE
シンポジウム申し込み

### ISSUE THREAD

**Issue by tkoyama010** [OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium#12]
早めにシンポジウムに申し込みたいです。

**Comment by tkoyama010** [comment]
done

**Comment by inabower** [comment]
申し込めていなかったので再開します

**Comment by inabower** [comment]
アブストは100〜200字とのことです。

**Comment by inabower** [comment]
それではこの内容で申し込んでもよろしいでしょうか。

みたいなのってプルリクみたいに複数人にリクエストすることってできますか？

**Comment by tkoyama010** [comment]
プルリクの場合レビューリクエストがそれにあたると思います。イシューは議論の場なので承認という機能はなかった気がします。
慣習的に
+1
と記入すると賛成で
-1
と記入すると反対という意味になります。

**Comment by tkoyama010** [comment]
+1 これでいいと思います。タイトル確定なので #3 も閉じますね。

**Comment by inabower** [comment]
+1

**Comment by inabower** [comment]
無事に申し込めたようです
