### ISSUE TITLE
:e-mail: Eメールアドレスの記入

### ISSUE THREAD

**Issue by tkoyama010** [OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium#32]
:e-mail: Eメールアドレスの記入が必要です。

**Comment by tkoyama010** [comment]
AuthorsEmailの部分です。
https://github.com/OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium/blob/8f3ab84d395e95ed039bfd79214d2ca66b8096f5/symposium/TeX/OpenFOAM-jp_OpenCAE_symposium.tex#L32

**Comment by inabower** [comment]
全員分載せますか？

**Comment by tkoyama010** [comment]
代表者一人でいいかと思います 👍

**Comment by matsubaraDaisuke** [comment]
稲葉さん，メールアドレスの登録お願いします．

**Comment by matsubaraDaisuke** [comment]
こちらで入力しておきます．

**Comment by matsubaraDaisuke** [comment]
記入済みだったのでクローズします．
