### ISSUE TITLE
著者名

### ISSUE THREAD

**Issue by tkoyama010** [OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium#4]
メンバーの方は著者名と所属を申告してください。学会の規約によりTwtiterIDも可です。

**Comment by tkoyama010** [comment]
@tkoyama010 OpenFOAM-jp

**Comment by inabower** [comment]
@inabower OpenFOAM-jp

**Comment by tkoyama010** [comment]
英語部分も修正する必要があります。
https://github.com/OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium/blob/52d5105426ef94ba9e09f583face83d2583efa63/symposium/TeX/template_OpenCAE_symposium.tex#L40-L54
あと、\daggerは一人目のみです。
https://github.com/OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium/blob/30a5934402fe9d80179fecdf45b35a865fc0603b/symposium/TeX/OpenFOAM-jp_OpenCAE_symposium.tex#L16-L23

**Comment by tkoyama010** [comment]
@matsubaraDaisuke さんも名前はTwitter名でいいですか？

**Comment by matsubaraDaisuke** [comment]
私はいつもどおり、本名とcae勉強会で行こうとおもいます。
統一性無くてすみません。

**Comment by tkoyama010** [comment]
いえいえ、反映しましたのでご確認お願いいたします。

**Comment by tkoyama010** [comment]
問題はないようなので閉じます。
