### ISSUE TITLE
セクションの順番

### ISSUE THREAD

**Issue by inabower** [OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium#41]
ある程度出揃ったので全体の流れに沿ったセクションの順番などについて議論していきます

1. **はじめに**
2. **Foundation版とESI版の違い**
  - 歴史とForkの説明
3. **ESI版のコントリビュート方法**
  - issueは誰でも建てられるけどPRはできないよ
4. **Foundation版のコントリビュート方法**
  - issue trackingシステムから行うよ
5. **Gitの使い方**
  - OpenFOAM-jp/OpenFOAM-jpを例にしたコマンドの説明
6. **GitHub および Travis による継続的インテグレーション**
  - OpenFOAM-jp/OpenFOAM-jpを例にしたTravis CIの説明
7. **OpenFOAM-jp**
  - 今やっていることの説明
8. **まとめ**

全体の流れに影響しそうな事案があればここでお願いします。

**Comment by inabower** [comment]
5,6章でOpenFOAM-jpを具体例に説明しているから、OpenFOAM-jpの賞は4章の後に持ってくるべきか

**Comment by tkoyama010** [comment]
+1 章の入れ替えはコンフリクトがあるのでマージが落ち着いたのちにdevelopブランチ上でお願いいたします。

**Comment by inabower** [comment]
これ時間かかるのでそのままで行く感じでいいでしょうか

良ければプラス1をお願いします
2になったらクローズで
