### ISSUE TITLE
目次

### ISSUE THREAD

**Issue by tkoyama010** [OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium#5]
目次を議論します。必要と思われる節を挙げてください。

**Comment by tkoyama010** [comment]
- はじめに
- まとめ
- Gitの使い方
- GitHub および Travis による継続的インテグレーション

**Comment by inabower** [comment]
・ESI版とFoundation版の違い
・ESI版コントリビュート方法
・Foundation版コントリビュート方法

**Comment by tkoyama010** [comment]
- GitHub および Travis による継続的インテグレーション

**Comment by tkoyama010** [comment]
とりあえず、今出ているものでセクションを作りますね。
