### ISSUE TITLE
:sparkles: 梗概提出時点でバージョンリリースをしましょう

### ISSUE THREAD

**Issue by tkoyama010** [OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium#53]
:bookmark:梗概提出時点でバージョンリリースをしましょう
梗概提出時点でリポジトリにタグをつけてリリースとしたいと思います。リリース用のプルリクエストをmasterブランチに対して行うのでdevelopブランチに全てのコミットが上げられていることを確認してください。

**Comment by inabower** [comment]
最後の方ローカルでやっちゃったのでまだプッシュしてないです
少々お待ちを

**Comment by inabower** [comment]
これがリリース版です

**Comment by inabower** [comment]
tagつきました
v2019.11.26
です

**Comment by tkoyama010** [comment]
ありがとうございました :arrow_up:
