### ISSUE TITLE
Travis CI を使用する

### ISSUE THREAD

**Issue by tkoyama010** [OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium#6]
"OpenFOAM-jp_OpenCAE_symposium.pdf"のビルド自動化が目的。

**Comment by inabower** [comment]
この場合ってGitHub上にTexLiveの入った環境を構築するんですか？

**Comment by tkoyama010** [comment]
リポジトリに設定ファイルを登録してTravis CI上でTeXをビルドする方式です。PDFをコミットするところまで、自動化できると思います。
目標は、ローカルでTeXのソースを修正しビルドせずにpush すると、Travis CI上でビルドされpdfがコミットされることです。ビルドの結果の可否はプルリクエストにお知らせが来ます。

**Comment by tkoyama010** [comment]
おそらくこれを参照すれば実現可能だと思います。:
https://github.com/harshjv/travis-ci-latex-pdf/blob/9331f5df7a955608e43e1bcc4b87efcb18d70d59/.travis.yml#L1-L18
使用しているのはluatexなのでそこは修正しないといけないですけど。
https://github.com/OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium/blob/52d5105426ef94ba9e09f583face83d2583efa63/symposium/TeX/Makefile#L3

**Comment by tkoyama010** [comment]
git push部分がうまくいっていまでした。RSA鍵にパスワードがかかっているのが原因のようです。
https://travis-ci.com/OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium/builds/124699736#L896-L902

**Comment by tkoyama010** [comment]
RSA鍵を更新しました。

**Comment by tkoyama010** [comment]
念のためmake cleanを追加しました。

**Comment by tkoyama010** [comment]
問題なさそうなので、閉じます。

**Comment by tkoyama010** [comment]
2回目のビルドでエラーが発生しました。
https://travis-ci.com/OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium/jobs/228509524#L192-L203

**Comment by tkoyama010** [comment]
以下で行うことによりエラーを回避しました。
https://github.com/OpenFOAM-jp/OpenFOAM-jp_OpenCAE_journal_and_symposium/blob/b150debabb2acdd8cd1b80ea16455e0af2060ab3/.travis.yml#L10-L12
